### ISSUE TITLE
Le principe d’inversion de contrôle est-il le "I" ou le “D” de “SOLID”?

### ISSUE THREAD

**Issue by aloupfor** [afsy/website#108]
https://github.com/afsy/website/blob/6da92435aadb1d9b796e1b726a586aba3bb73bf3/src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_02.html.twig#L130

Le principe d’inversion de contrôle est-il le "I" ou le “D” de “SOLID”?

**Comment by hhamon** [comment]
D => Dependency Inversion
I => Interface Segregation

L'inversion de contrôle est encore autre chose !
