### ISSUE TITLE
On [Day-21], typos on the configuration of rabbitMq

### ISSUE THREAD

**Issue by mickaelandrieu** [afsy/website#76]
Hi,
on the last parameters, there is an extra space.
I failed to create a PR (404 when I try to edit directly o_O).

Regards,

**Comment by Nek-** [comment]
What rabbitmq ? :/

**Comment by mickaelandrieu** [comment]
I'm not sure this issue is always relevant (we are in 2015 now and the website have changed a lot).

Closed.
