### ISSUE TITLE
Demande de droits

### ISSUE THREAD

**Issue by Nek-** [afsy/website#83]
Hello,

J'aimerais bien avoir le droit de commit / PR / Merge sur le projet histoire que le site bouge un peu parce qu'il est bien bugué et qu'il n'est pas vraiment maintenu pour le moment.

C'est possible ?

Note: je vais faire des PR pour toutes les modifs ne vous inquiétez pas.

Maxime.

**Comment by hhamon** [comment]
Hello Maxime,

Je viens de t'ajouter au répo.

Par contre pour les déploiements, c'est Xavier Lacot qui a toutes les infos il me semble.

SensioLabs
Hugo Hamon // Head of training
hugo.hamon@sensiolabs.com<mailto:hugo.hamon@sensiolabs.com>
<https://white.sensio.net/owa/redir.aspx?C=kIwKRgXTOk6GR5IXB3s4RdQLBjK1bdEInbPV01sNbo-k-82WhnPTYABHFdp0MIw8jSXc38zyj9o.&URL=mailto%3aannesophie.bachelard%40sensiolabs.com>Direct line: +33 (0)1 40 99 82 11
General office: +33 (0)1 40 99 80 80

92-98 Bd. Victor Hugo, entrée A2, 10e étage
92115 Clichy Cedex - France

________________________________
De : Maxime Veber [notifications@github.com]
Envoyé : lundi 27 juillet 2015 23:24
À : afsy/website
Objet : [website] Demande de droits (#83)


Hello,

J'aimerais bien avoir le droit de commit / PR / Merge sur le projet histoire que le site bouge un peu parce qu'il est bien bugué et qu'il n'est pas vraiment maintenu pour le moment.

C'est possible ?

Note: je vais faire des PR pour toutes les modifs ne vous inquiétez pas.

Maxime.
